"""Add locked field to User model

Revision ID: 6acfd2f90511
Revises: 
Create Date: 2025-04-08 18:23:06.021775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acfd2f90511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('rated_student_id', sa.INTEGER(), nullable=False),
    sa.Column('moral', sa.VARCHAR(length=1), nullable=False),
    sa.Column('intelligence', sa.VARCHAR(length=1), nullable=False),
    sa.Column('physical', sa.VARCHAR(length=1), nullable=False),
    sa.Column('aesthetic', sa.VARCHAR(length=1), nullable=False),
    sa.Column('labor', sa.VARCHAR(length=1), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rated_student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'rated_student_id', name='unique_rating')
    )
    # ### end Alembic commands ###
